[xpaths]
chatbot_launcher = "//button[@class='rcw-launcher']"
carousel_img = "//img[@class='carousel-img']"
avatar = "//img[@class='rcw-avatar']"
begin_english = "//button[contains(., 'Begin in English')]"
begin_spanish = "//button[contains(., 'Empezar en español')]"
begin_french = "//button[contains(., 'Allez en français')]"
begin_creole = "//button[contains(., 'Kòmanse an kreyòl ayisyen')]"
begin_arabic = "//button[contains(., 'ابدأ باللغة العربية')]"
welcome_screen = "//div[contains(@class, 'welcome-screen')]"
language_buttons = "//button[contains(@class, 'welcome-screen-option-button')]"
terms_link = "//span[contains(@class, 'welcome-screen-footer')]"
ticker = "//span[contains(@class, 'welcome-screen-title fade-text')]"
bot_logo = "//div[@class='rcw-botIcon']"
NIJC_assistant = "//span[@class='rcw-title']"
top_heading_text = "//span[@class='rcw-help-you-with-title-header']" 
end_chat = "//div[@class='rcw-item rcw-item-two']//li[@title='Finalizar Chat']"   
schedule_appointment = "//span[normalize-space()='Schedule or Change Appointment']"
user_selection = "//p[normalize-space()='Schedule or Change Appointment']"
chatbot_response = "//span[@class='question-route-label']"
chatbot_options = "//ul[@aria-label='Available options to select']//li//button[contains(@title,'Request a New Appointment')]"
[admin_portal]
login_with_sso = "//button[@id='login-button']"
email_input = "//input[@id='i0116']"
next_button = "//input[@id='idSIButton9']"
password_input = "//input[@id='i0118']"
sign_in_button = "//input[@id='idSIButton9']"
forgot_password_link = "//a[@id='idA_PWD_ForgotPassword']"
stay_signed_in_yes = "//input[@id='idSIButton9']"
stay_signed_in_no = "//input[@id='idBtn_Back']"
manage_calendars_menu = "//span[text()='Manage Calendars']"
dashboard_menu = "//span[text()='Dashboard']"
page_header = "//h1"
add_new_calendar_btn = "//button[@id='add-calendar-btn']"
calendar_action_menu = "//tbody/tr[1]//button[@aria-label='more']"
edit_option = "//li[text()='Edit']"
duplicate_option = "//li[text()='Duplicate']"
delete_option = "//li[text()='Delete']"
calendar_name_input = "//input[@name='calendarName']"
 